name: Deploy to GitHub Pages via Artifact

on:
  workflow_run:
    workflows: ["CI"]  # automatic deploy after CI
    types: [completed]
  workflow_dispatch:    # manual trigger from GitHub UI

jobs:
  build:
    # Run on manual dispatch or any successful CI run
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    concurrency:
      group: 'pages'
      cancel-in-progress: true
    defaults:
      run:
        shell: bash
        working-directory: currency-converter-app

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          # For manual runs (workflow_dispatch) github.event.workflow_run is undefined,
          # so fall back to the branch ref associated with the workflow.
          ref: ${{ github.event_name == 'workflow_dispatch' && github.ref || github.event.workflow_run.head_sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (npm ci)
        run: npm ci --ignore-scripts

      - name: Build static web export (Expo)
        run: npm run export:web

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./currency-converter-app/dist-web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write     # to deploy to Pages
      id-token: write  # to authenticate the deployment via OIDC
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 