name: Build & Deploy Expo Web to GH Pages

on:
  push:
    branches:
      - retry-githubpages      # trigger on the working branch
  workflow_dispatch:          # allow manual runs

permissions:
  contents: write             # needed for the deployment step to push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: currency-converter-app  # all commands run from the app dir

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('currency-converter-app/package-lock.json') }}

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build web assets
        # This runs the export script defined in package.json which outputs to dist-web/
        run: npm run export:web

      - name: Deploy to GitHub Pages (gh-pages branch)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: currency-converter-app/dist-web
          force_orphan: true         # keep gh-pages history slim
          commit_message: Deploy web build for ${{ github.sha }} 